apiVersion: v1
description: Rabbitmq metrics exporter for prometheus
name: prometheus-rabbitmq-exporter
<<<<<<< HEAD
version: 1.7.0
=======
version: 1.6.1
>>>>>>> f3471fec (allow rabbitmq env vars to be overriden by supplying an external configmap)
appVersion: v0.29.0
home: https://github.com/kbudde/rabbitmq_exporter
sources:
- https://github.com/kbudde/rabbitmq_exporter
maintainers:
- name: desaintmartin
  email: cedric@desaintmartin.fr
- name: iamabhishek-dubey
  email: abhishekbhardwaj510@gmail.com
- name: juanchimienti
  email: juan.chimienti@gmail.com
- name: monotek
  email: monotek23@gmail.com
